version: '3.1'
services:
  mongo:
    image: mongo
    ports: 
      - 27016:27017
    volumes:
      - /home/arturl/dev/EW_PL/db-files:/data/db
    networks:
      - ew_pl_network
  api:
    build: 
      context: ./api
    depends_on:
      - mongo
    ports:
      - 7777:7777
    networks:
      - ew_pl_network

  client:
    build: 
      context: ./client
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
      - ew_pl_network

networks:
  ew_pl_network:
    driver: bridge
